version: "3.8"
services:
  backend:
    image: jyguru/pathological-backend:${RELEASE_TAG}
    build:
      context: ./
      dockerfile: deployment/backend.dockerfile
  frontend:
    image: jyguru/pathological-frontend:${RELEASE_TAG}
    build:
      context: ./
      dockerfile: deployment/frontend.dockerfile
