version: "3.8"
services:
  backend:
    image: github.com/otherband/pathological-backend
    entrypoint: sh ./run_backend.sh
    environment:
      - APP_HOSTNAME=0.0.0.0
      - APP_WORKERS=1
      - APP_ROOT_DIR=backend/src/pathological
      - APP_PORT=80
      - APP_THREADS=3
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    healthcheck:
      test: curl --fail localhost:80/actuator/health || exit 1
      interval: 10s
    ports:
      - "5000:80"
  frontend:
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    image: github.com/otherband/pathological-frontend
    ports:
      - "8080:80"

