version: "3.8"
services:
  frontend:
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    image: github.com/otherband/pathological-frontend
    ports:
      - "8080:80"
  backend:
    hostname: backend
    ports:
      - "5000:5000"
    image: github.com/otherband/pathological-backend
    entrypoint: sh ./run_backend.sh
    environment:
      - APP_HOSTNAME=backend
      - APP_WORKERS=1
      - APP_ROOT_DIR=backend/src/pathological
      - APP_PORT=5000
      - APP_THREADS=3
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    healthcheck:
      test: curl --fail backend:5000/actuator/health || exit 1
      interval: 10s
