name: Build

on:
  push:
    branches: [ master, '3' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      RELEASE_TAG:
        description: "Enter desired release tag"
        required: true
      DOCKER_STAGE:
        description: "Whether to build and push docker images"
        default: false


jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt;
      - name: Install backend
        run: pip install .;
      - name: run tests
        run: python3 -m unittest discover -s test/ -t test/ -v;
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: "Node set-up"
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -- --mode=production
  build-docker-images:
    if: "${{github.event.inputs.DOCKER_STAGE}}"
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: "${{ github.event.inputs.RELEASE_TAG }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: KengoTODA/actions-setup-docker-compose@v1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build images
        run: docker-compose build
      - name: push images
        run: docker-compose push
