openapi: 3.0.0
info:
  title: Multiplayer Game Events API
  version: 1.0.0
components:
  schemas:
    MultiplayerGameEvent:
      type: object
    BasicPlayerData:
      type: object
      properties:
        player_id:
          type: string
    GameStarting:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            game_id:
              type: string
            connected_players:
              type: array
              items:
                $ref: '#/components/schemas/BasicPlayerData'
            start_game_delay:
              type: integer
            message:
              type: string
    GameStarted:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            game_id:
              type: string
            connected_players:
              type: array
              items:
                $ref: '#/components/schemas/BasicPlayerData'
            message:
              type: string
    ChallengeRequested:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            player_id:
              type: string
            challenge_id:
              type: string
    PlayerJoin:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            player_id:
              type: string
            game_id:
              type: string
            connected_players:
              type: array
              items:
                $ref: '#/components/schemas/BasicPlayerData'
    PlayerLeft:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            player_id:
              type: string
            game_id:
              type: string
            connected_players:
              type: array
              items:
                $ref: '#/components/schemas/BasicPlayerData'
