openapi: 3.0.0
info:
  title: Multiplayer Game Events API
  version: 1.0.0
paths:
  /multiplayer-game-events:
    post:
      summary: Send a multiplayer game event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/GameStarting'
                - $ref: '#/components/schemas/GameStarted'
                - $ref: '#/components/schemas/ChallengeRequested'
                - $ref: '#/components/schemas/PlayerJoin'
                - $ref: '#/components/schemas/PlayerLeft'
      responses:
        '200':
          description: Event received successfully
components:
  schemas:
    MultiplayerGameEvent:
      type: object
    BasicPlayerData:
      type: object
      properties:
        playerId:
          type: string
    GameStarting:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            gameId:
              type: string
            connectedPlayers:
              type: array
              items:
                $ref: '#/components/schemas/BasicPlayerData'
            startGameDelay:
              type: integer
            message:
              type: string
    GameStarted:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            gameId:
              type: string
            connectedPlayers:
              type: array
              items:
                $ref: '#/components/schemas/BasicPlayerData'
            message:
              type: string
    ChallengeRequested:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            playerId:
              type: string
            challengeId:
              type: string
    PlayerJoin:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            playerId:
              type: string
            gameId:
              type: string
            connectedPlayers:
              type: array
              items:
                $ref: '#/components/schemas/BasicPlayerData'
    PlayerLeft:
      allOf:
        - $ref: '#/components/schemas/MultiplayerGameEvent'
        - type: object
          properties:
            playerId:
              type: string
            gameId:
              type: string
            connectedPlayers:
              type: array
              items:
                $ref: '#/components/schemas/BasicPlayerData'
